

platform :ios, '9.0'

target 'TuyaSmartLightKit_Example' do
  pod 'TuyaSmartLightKit', :path => '../'
  pod 'TuyaSmartDemo', :path => '../', :subspecs => [
   'Base',
   'Login',
   'DeviceList',
   'AddDevice',
   'SmartScene',
   'UserInfo']
  pod 'MBProgressHUD', '~> 0.9.2'

  target 'TuyaSmartLightKit_Tests' do
    inherit! :search_paths

  end
end
